# Generated by Django 5.1.2 on 2024-10-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='encrypted_choice',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
